<?php

use Livewire\Volt\Component;
use App\Models\Territory;
use App\Models\Lane;
use App\Models\Freight;
use App\Models\WorksheetHeader;
use App\Models\User;
use Livewire\Attributes\Computed;

new class extends Component {
    public Territory $territory;

    public $backendStaff = ['superadmin', 'admin', 'marketing logistics associate', 'procurement logistics associate', 'operations logistics associate', 'logistics operations executive'];

    public function mount(Territory $territory)
    {
        $this->territory = $territory->load(['users.roles', 'countries', 'provinces.zimbabweCities', 'zimbabweCities']);
    }

    /**
     * This query finds ANY user in the system whose business location
     * matches the geographic bounds of this territory.
     */
    protected function getUsersInGeographicScope($role = null)
    {
        $allowedCountryNames = $this->territory->countries->pluck('name')->toArray();

        $allowedCityNames = $this->territory->zimbabweCities
            ->pluck('name')
            ->concat($this->territory->provinces->flatMap->zimbabweCities->pluck('name'))
            ->unique()
            ->toArray();

        $query = User::whereHas('buslocation', function ($q) use ($allowedCountryNames, $allowedCityNames) {
            $q->where(function ($sub) use ($allowedCountryNames, $allowedCityNames) {
                // Zimbabwe check
                $sub->where(function ($zim) use ($allowedCityNames) {
                    $zim->where('country', 'Zimbabwe')->whereIn('city', $allowedCityNames);
                })
                    // Non-Zimbabwe check
                    ->orWhere(function ($other) use ($allowedCountryNames) {
                        $other->where('country', '!=', 'Zimbabwe')->whereIn('country', $allowedCountryNames);
                    });
            });
        });

        // FIX START: Replace ->role($role) with whereHas
        if ($role) {
            $query->whereHas('roles', function ($q) use ($role) {
                $q->where('name', $role);
            });
        }
        // FIX END

        return $query;
    }

    #[Computed]
    public function stats()
    {
        // 1. Backend Staff (Fixed Assignment via pivot table)
        $assignedBackend = $this->territory->users->filter(fn($u) => $u->hasAnyRole($this->backendStaff));

        // 2. Carriers & Shippers (Dynamic Discovery via BusLocation)
        $carrierIds = $this->getUsersInGeographicScope('carrier')->pluck('id');
        $shipperIds = $this->getUsersInGeographicScope('shipper')->pluck('id');

        // 3. Growth: Combined recent users (Staff assigned OR Clients in location)
        $recentClients = User::whereIn('id', $carrierIds->concat($shipperIds))
            ->where('created_at', '>=', now()->subDays(14))
            ->count();
        $recentStaff = $assignedBackend->where('created_at', '>=', now()->subDays(14))->count();

        return [
            'carriers' => $carrierIds->count(),
            'shippers' => $shipperIds->count(),
            'backend' => $assignedBackend->count(),
            'recent' => $recentClients + $recentStaff,

            // Activity is strictly tied to the dynamic list of users found in the scope
            'vehicles' => Lane::whereIn('carrier_id', $carrierIds)->count(),
            'loads' => Freight::whereIn('shipper_id', $shipperIds)->count(),

            // Worksheets (usually generated by staff or specific users)
            // We'll count worksheets for both assigned staff and scoped clients
            'worksheets' => WorksheetHeader::whereIn('user_id', $carrierIds->concat($shipperIds)->concat($assignedBackend->pluck('id')))->count(),
            'shared' => WorksheetHeader::whereIn('user_id', $carrierIds->concat($shipperIds)->concat($assignedBackend->pluck('id')))
                ->has('sharedWith')
                ->count(),
        ];
    }

    /**
     * Merges Assigned Staff and Scoped Clients for the UI list
     */
    #[Computed]
    public function allPersonnel()
    {
        $staff = $this->territory->users->filter(fn($u) => $u->hasAnyRole($this->backendStaff));

        // Using whereHas instead of role() here as well
        $clients = $this->getUsersInGeographicScope()->whereHas('roles', fn($q) => $q->whereIn('name', ['carrier', 'shipper']))->with('roles')->get();

        return $staff->concat($clients)->sortBy('organisation');
    }
    #[Computed]
    public function marketHealth()
    {
        $loads = $this->stats['loads'];
        $trucks = $this->stats['vehicles'];

        // Calculate ratio of loads to trucks
        $ratio = $trucks > 0 ? round($loads / $trucks, 1) : $loads;

        return [
            'ratio' => $ratio,
            'status' => match (true) {
                $loads == 0 && $trucks == 0 => 'No Data',
                $loads > $trucks * 1.5 => 'Undersupplied',
                $trucks > $loads * 1.5 => 'Overcapacity',
                default => 'Balanced',
            },
            'color' => match (true) {
                $loads == 0 && $trucks == 0 => 'zinc',
                $loads > $trucks * 1.5 => 'orange',
                $trucks > $loads * 1.5 => 'indigo',
                default => 'emerald',
            },
        ];
    }

    #[Computed]
    public function cityDistribution()
    {
        // Get the IDs of all carriers and shippers in this territory
        $clientIds = $this->getUsersInGeographicScope()->whereHas('roles', fn($q) => $q->whereIn('name', ['carrier', 'shipper']))->pluck('id');

        // Count users grouped by their buslocation city
        return \App\Models\Buslocation::whereIn('user_id', $clientIds)->select('city', \DB::raw('count(*) as total'))->groupBy('city')->orderByDesc('total')->get();
    }
}; ?>

<div class="p-8">
    {{-- 1. HEADER SECTION --}}
    <div
        class="mb-8 flex flex-col md:flex-row md:items-center justify-between gap-6 bg-zinc-50 dark:bg-zinc-950 p-6 rounded-[2.5rem] border border-zinc-100 dark:border-zinc-800">
        <div class="flex items-center gap-4">
            <div class="size-12 bg-lime-600 rounded-2xl flex items-center justify-center shadow-lg">
                <flux:icon.map class="size-6 text-white" />
            </div>
            <div>
                <flux:heading size="xl"
                    class="tracking-tighter font-black uppercase text-zinc-900 dark:text-white leading-none">
                    {{ $territory->name }}
                </flux:heading>
                <div class="mt-2 flex items-center gap-2">
                    <flux:button href="{{ route('territories.index') }}" variant="ghost" size="sm" icon="list-bullet"
                        wire:navigate>All Territories</flux:button>
                    <span class="text-zinc-300">|</span>
                    <flux:button href="{{ route('territories.create') }}" variant="ghost" size="sm" icon="plus"
                        wire:navigate>Create New</flux:button>
                </div>
            </div>
        </div>

        <flux:button href="{{ route('territories.edit', $territory) }}" icon="pencil-square" variant="primary"
            class="!rounded-xl" wire:navigate>
            Edit Jurisdiction
        </flux:button>
    </div>
    {{-- 1b market pulse --}}
    {{-- ANALYTICS OVERLAY --}}
    <div class="grid grid-cols-1 lg:grid-cols-3 gap-6 mb-10">
        {{-- Market Pulse Card --}}
        <div
            class="lg:col-span-1 p-6 bg-white dark:bg-zinc-900 border border-zinc-200 dark:border-zinc-800 rounded-[2.5rem] shadow-sm">
            <div class="flex items-center justify-between mb-6">
                <div class="flex items-center gap-2">
                    <flux:icon.chart-bar class="size-5 text-zinc-400" />
                    <flux:heading size="sm" class="uppercase tracking-widest text-zinc-500">Market Pulse
                    </flux:heading>
                </div>
                <flux:badge color="{{ $this->marketHealth['color'] }}" variant="pill" size="sm"
                    class="font-black uppercase">
                    {{ $this->marketHealth['status'] }}
                </flux:badge>
            </div>

            <div class="flex items-end gap-3">
                <span class="text-5xl font-black tracking-tighter text-zinc-900 dark:text-white">
                    {{ $this->marketHealth['ratio'] }}
                </span>
                <div class="pb-2">
                    <p class="text-xs font-bold text-zinc-500 leading-none">Loads per</p>
                    <p class="text-xs font-bold text-zinc-500 leading-none">Vehicle</p>
                </div>
            </div>

            <div class="mt-6 pt-6 border-t border-zinc-100 dark:border-zinc-800">
                <p class="text-[11px] text-zinc-400 leading-relaxed">
                    This ratio measures demand (Freight) against supply (Lanes).
                    A higher number suggests a need for more Carriers in this jurisdiction.
                </p>
            </div>
        </div>

        {{-- City Distribution Card --}}
        <div
            class="lg:col-span-2 p-6 bg-white dark:bg-zinc-900 border border-zinc-200 dark:border-zinc-800 rounded-[2.5rem] shadow-sm">
            <flux:heading size="sm" class="uppercase tracking-widest text-zinc-500 mb-6 flex items-center gap-2">
                <flux:icon.map-pin class="size-5 text-zinc-400" />
                Personnel Concentration
            </flux:heading>

            <div class="grid grid-cols-2 sm:grid-cols-3 gap-4">
                @forelse($this->cityDistribution as $dist)
                    <div
                        class="p-4 bg-zinc-50 dark:bg-zinc-950 rounded-2xl border border-zinc-100 dark:border-zinc-800">
                        <p class="text-[10px] font-black uppercase text-zinc-400 mb-1 truncate">{{ $dist->city }}</p>
                        <div class="flex items-baseline gap-1">
                            <span class="text-xl font-black text-zinc-800 dark:text-zinc-200">{{ $dist->total }}</span>
                            <span class="text-[10px] text-zinc-500 font-bold uppercase">Users</span>
                        </div>
                    </div>
                @empty
                    <div class="col-span-full py-4 text-center text-xs text-zinc-400 italic">
                        No geographic concentration data available.
                    </div>
                @endforelse
            </div>
        </div>
    </div>
    {{-- 2. ACTIVITY METRICS DASHBOARD --}}
    <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4 mb-10">
        {{-- Loads (Freight) --}}
        <div
            class="p-6 bg-orange-50 dark:bg-orange-950/20 border border-orange-100 dark:border-orange-900/50 rounded-[2rem]">
            <div class="flex justify-between items-start">
                <flux:icon.briefcase class="size-6 text-orange-600" />
                <flux:badge color="orange" variant="subtle" size="sm" class="font-black">
                    {{ $this->stats['shippers'] }} Shippers</flux:badge>
            </div>
            <p class="mt-4 text-3xl font-black text-orange-900 dark:text-orange-200">{{ $this->stats['loads'] }}</p>
            <p class="text-[10px] font-bold uppercase tracking-widest text-orange-600/70">Available Loads</p>
        </div>

        {{-- Vehicles (Lanes) --}}
        <div
            class="p-6 bg-indigo-50 dark:bg-indigo-950/20 border border-indigo-100 dark:border-indigo-900/50 rounded-[2rem]">
            <div class="flex justify-between items-start">
                <flux:icon.truck class="size-6 text-indigo-600" />
                <flux:badge color="indigo" variant="subtle" size="sm" class="font-black">
                    {{ $this->stats['carriers'] }} Carriers</flux:badge>
            </div>
            <p class="mt-4 text-3xl font-black text-indigo-900 dark:text-indigo-200">{{ $this->stats['vehicles'] }}</p>
            <p class="text-[10px] font-bold uppercase tracking-widest text-indigo-600/70">Active Vehicles</p>
        </div>

        {{-- Worksheets (WorksheetHeader) --}}
        <div
            class="p-6 bg-emerald-50 dark:bg-emerald-950/20 border border-emerald-100 dark:border-emerald-900/50 rounded-[2rem]">
            <div class="flex justify-between items-start">
                <flux:icon.document-text class="size-6 text-emerald-600" />
                <flux:badge color="emerald" variant="subtle" size="sm" class="font-black">
                    {{ $this->stats['shared'] }} Shared</flux:badge>
            </div>
            <p class="mt-4 text-3xl font-black text-emerald-900 dark:text-emerald-200">{{ $this->stats['worksheets'] }}
            </p>
            <p class="text-[10px] font-bold uppercase tracking-widest text-emerald-600/70">Total Worksheets</p>
        </div>

        {{-- Backend Staff --}}
        <div class="p-6 bg-zinc-100 dark:bg-zinc-800 border border-zinc-200 dark:border-zinc-700 rounded-[2rem]">
            <div class="flex justify-between items-start">
                <flux:icon.shield-check class="size-6 text-zinc-600" />
                <flux:badge color="zinc" variant="subtle" size="sm" class="font-black">
                    +{{ $this->stats['recent'] }} New</flux:badge>
            </div>
            <p class="mt-4 text-3xl font-black text-zinc-900 dark:text-zinc-100">{{ $this->stats['backend'] }}</p>
            <p class="text-[10px] font-bold uppercase tracking-widest text-zinc-500">Backend Personnel</p>
        </div>
    </div>

    {{-- 3. GEOGRAPHIC SCOPE --}}
    <div class="grid grid-cols-1 md:grid-cols-3 gap-6 mb-10">
        {{-- Countries --}}
        <div class="p-6 bg-white dark:bg-zinc-900 border border-zinc-200 dark:border-zinc-800 rounded-[2rem] shadow-sm">
            <p class="text-[10px] font-black uppercase tracking-widest text-amber-600 mb-3">Regional Countries</p>
            <div class="flex flex-wrap gap-2">
                @forelse($territory->countries as $country)
                    <flux:badge color="amber" variant="subtle" class="rounded-lg">{{ $country->name }}</flux:badge>
                @empty
                    <span class="text-xs text-zinc-400 italic">Global/Local scope</span>
                @endforelse
            </div>
        </div>

        {{-- Provinces --}}
        <div class="p-6 bg-white dark:bg-zinc-900 border border-zinc-200 dark:border-zinc-800 rounded-[2rem] shadow-sm">
            <p class="text-[10px] font-black uppercase tracking-widest text-indigo-600 mb-3">Full Provinces</p>
            <div class="flex flex-wrap gap-2">
                @forelse($territory->provinces as $province)
                    <flux:badge color="indigo" variant="subtle" class="rounded-lg">{{ $province->name }}</flux:badge>
                @empty
                    <span class="text-xs text-zinc-400 italic">No full provinces</span>
                @endforelse
            </div>
        </div>

        {{-- Cities --}}
        <div
            class="p-6 bg-white dark:bg-zinc-900 border border-zinc-200 dark:border-zinc-800 rounded-[2rem] shadow-sm">
            <p class="text-[10px] font-black uppercase tracking-widest text-emerald-600 mb-3">Specific Cities</p>
            <div class="flex flex-wrap gap-2">
                @forelse($territory->zimbabweCities as $city)
                    <flux:badge color="emerald" variant="subtle" class="rounded-lg">{{ $city->name }}</flux:badge>
                @empty
                    <span class="text-xs text-zinc-400 italic">No specific cities</span>
                @endforelse
            </div>
        </div>
    </div>

    <hr class="border-zinc-100 dark:border-zinc-800 mb-10" />

    {{-- 4. ASSIGNED PERSONNEL GRID --}}
    <div class="mb-6 flex items-center justify-between">
        <div class="flex items-center gap-3">
            <flux:icon.users variant="mini" class="size-5 text-zinc-400" />
            <flux:heading size="lg">Logistics Personnel ({{ $territory->users->count() }})</flux:heading>
        </div>
    </div>

    <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-4">
        @forelse ($territory->users as $user)
            <div class="relative" x-data="{ showContact: false }">
                {{-- Tooltip and Card logic remains identical to your working template --}}
                <div x-show="showContact" x-transition x-cloak
                    class="absolute z-50 bottom-full left-0 mb-3 w-72 p-5 bg-zinc-900 text-white rounded-[1.5rem] shadow-2xl border border-zinc-800 pointer-events-none">
                    <div class="space-y-3">
                        <div>
                            <p class="text-[9px] font-black text-indigo-400 uppercase tracking-widest mb-1">Assigned
                                Role</p>
                            <div class="flex flex-wrap gap-1">
                                @foreach ($user->roles as $role)
                                    <span
                                        class="text-[10px] font-bold bg-white/10 px-2 py-0.5 rounded-md border border-white/5">{{ $role->name }}</span>
                                @endforeach
                            </div>
                        </div>
                        <div class="pt-2 border-t border-zinc-800 space-y-2 text-[11px]">
                            <p><span class="text-zinc-500 font-bold uppercase text-[9px]">Contact:</span>
                                {{ $user->contact_person }}</p>
                            <p><span class="text-zinc-500 font-bold uppercase text-[9px]">Phone:</span>
                                {{ $user->contact_phone }}</p>
                            <p><span class="text-emerald-500 font-bold uppercase text-[9px]">WhatsApp:</span>
                                {{ $user->whatsapp ?? $user->contact_phone }}</p>
                            <p><span class="text-zinc-500 font-bold uppercase text-[9px]">Email:</span>
                                {{ $user->email }}</p>
                        </div>
                    </div>
                    <div
                        class="absolute -bottom-1 left-8 size-2 bg-zinc-900 rotate-45 border-r border-b border-zinc-800">
                    </div>
                </div>

                <a href="{{ route('users.show', $user->slug) }}" wire:navigate @mouseenter="showContact = true"
                    @mouseleave="showContact = false"
                    class="group block p-6 bg-white dark:bg-zinc-900 border border-zinc-200 dark:border-zinc-800 rounded-[2.5rem] hover:border-lime-500 hover:shadow-xl transition-all duration-300">
                    <div class="space-y-3">
                        <div class="flex items-center justify-between">
                            <p
                                class="text-[10px] font-black text-indigo-600 dark:text-indigo-400 uppercase tracking-widest">
                                {{ $user->organisation }}</p>
                            <flux:icon.chevron-right variant="mini"
                                class="size-4 text-zinc-300 group-hover:text-indigo-500 transition-colors" />
                        </div>
                        <div>
                            <p class="text-sm font-black text-zinc-800 dark:text-zinc-100 leading-tight">
                                {{ $user->contact_person }}</p>
                            <div class="mt-2 flex flex-wrap gap-1">
                                @foreach ($user->roles->take(1) as $role)
                                    <span
                                        class="text-[9px] font-black uppercase px-2 py-0.5 bg-zinc-100 dark:bg-zinc-800 text-zinc-500 rounded-md">
                                        {{ $role->name }}
                                    </span>
                                @endforeach
                                @if ($user->roles->count() > 1)
                                    <span
                                        class="text-[9px] font-black text-zinc-400">+{{ $user->roles->count() - 1 }}</span>
                                @endif
                            </div>
                        </div>
                    </div>
                </a>
            </div>
        @empty
            <div
                class="col-span-full py-16 flex flex-col items-center justify-center border-2 border-dashed border-zinc-200 dark:border-zinc-800 rounded-[3rem]">
                <flux:icon.user-plus class="size-12 text-zinc-200 mb-4" />
                <p class="text-zinc-400 font-medium">No personnel assigned to this jurisdiction.</p>
            </div>
        @endforelse
    </div>
</div>
